#pragma once

#ifdef AUDIO_ENABLE
#define STARTUP_SONG SONG(PLANCK_SOUND)
#endif

#define MIDI_BASIC

#define ENCODER_RESOLUTION 4

#undef RGB_MATRIX_HUE_STEP
#define RGB_MATRIX_HUE_STEP 24

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 900000

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 17

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 3

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 29

#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED 16

#define CAPS_LOCK_STATUS
#define USB_POLLING_INTERVAL_MS 10
#define SERIAL_NUMBER "EmP5b/orAVal"
#define LAYER_STATE_16BIT

#define RGB_MATRIX_STARTUP_SPD 60

